### ISSUE TITLE
【APP】数値の範囲を変更

### ISSUE THREAD

**Issue by kohei-okazaki** [kohei-okazaki/work-3g#684]
DBのシーケンスIDなどのカラムをINT型で定義しているのをやめて
もっと大きな値でも対応できるようにする

**Comment by kohei-okazaki** [comment]
`Caused by: org.apache.ibatis.type.TypeException: Could not resolve type alias 'BIGINT'.  Cause: java.lang.ClassNotFoundException: Cannot find class: BIGINT
	at org.apache.ibatis.type.TypeAliasRegistry.resolveAlias(TypeAliasRegistry.java:120) ~[mybatis-3.5.6.jar:3.5.6]
	at org.apache.ibatis.builder.BaseBuilder.resolveAlias(BaseBuilder.java:149) ~[mybatis-3.5.6.jar:3.5.6]
	at org.apache.ibatis.builder.BaseBuilder.resolveClass(BaseBuilder.java:116) ~[mybatis-3.5.6.jar:3.5.6]
	... 66 common frames omitted
Caused by: java.lang.ClassNotFoundException: Cannot find class: BIGINT
	at org.apache.ibatis.io.ClassLoaderWrapper.classForName(ClassLoaderWrapper.java:196) ~[mybatis-3.5.6.jar:3.5.6]
	at org.apache.ibatis.io.ClassLoaderWrapper.classForName(ClassLoaderWrapper.java:89) ~[mybatis-3.5.6.jar:3.5.6]
	at org.apache.ibatis.io.Resources.classForName(Resources.java:261) ~[mybatis-3.5.6.jar:3.5.6]
	at org.apache.ibatis.type.TypeAliasRegistry.resolveAlias(TypeAliasRegistry.java:116) ~[mybatis-3.5.6.jar:3.5.6]
	... 68 common frames omitted`

**Comment by kohei-okazaki** [comment]
BIGINT型からJavaのLong型への変換を自動でやってくれず、サーバ起動時に落ちた
mybatis-config.xmlに以下の定義を追加すればできるようになった
`<typeAlias type="java.lang.Long" alias="BIGINT" />`
