### ISSUE TITLE
【APP】スラックAPIエラー

### ISSUE THREAD

**Issue by kohei-okazaki** [kohei-okazaki/work-3g#920]
以下のログが出てスラック通知ができなくなっている（類似エラー=https://github.com/Itiviti/simple-slack-api/issues/108）
`
[error] Caused by: java.lang.NullPointerException
[error]     at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connectImpl(SlackWebSocketSessionImpl.java:278)
[error]     at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connect(SlackWebSocketSessionImpl.java:230)
`

**Comment by kohei-okazaki** [comment]
https://github.com/kohei-okazaki/work-3g/pull/921
